name: Deploy no Netlify 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
      run: |
        curl -sL https://github.com/netlify/cli/releases/download/v7.0.0/netlify-cli-linux-x86_64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/netlify /usr/local/bin
        netlify deploy --prod --dir=dist
