name: Continuous Delivery

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }} 
      run: |
        netlify deploy --prod --dir=dist  # 'dist' é a pasta padrão de build do Vite
